name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 8
      - name: Build
        run: |
          ant generate-all
          ant compile
          ant compile_native
          ant jars
      - name: Create Artifact Zip
        run: |
          mkdir artifact
          cp temp/jar/* artifact | true
          cp -r libs/macosx artifact/natives | true
          zip artifact.zip artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: x86_64_build
          path: artifact.zip
