name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build with Ant
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 8
      - name: Build
        run: |
          ant generate-all
          ant compile
          ant compile_native
          ant jars
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: all_build
          path: libs
